# Generated by Django 5.0.2 on 2025-01-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="author",
            field=models.TextField(),
        ),
    ]
